"""tg_id unique

Revision ID: 20b62b658fed
Revises: 837db3758e2a
Create Date: 2023-09-02 16:16:19.251129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20b62b658fed'
down_revision: Union[str, None] = '837db3758e2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_tg_id', table_name='user')
    op.create_index(op.f('ix_user_tg_id'), 'user', ['tg_id'], unique=True)
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_user_tg_id'), table_name='user')
    op.create_index('ix_user_tg_id', 'user', ['tg_id'], unique=False)
    # ### end Alembic commands ###
